image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  # Common
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_REGION: $AWS_REGION
  S3_BUCKET_NAME: $S3_BUCKET_NAME
  CDN_DISTRIBUTION_ID: $CDN_DISTRIBUTION_ID

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

Build:
  stage: build
  image: node:11
  script:
    - npm install
    - npm run build:dev
  artifacts:
    paths:
      - public/
    expire_in: 1 day
  only:
    - master

Deploy:
  stage: deploy
  before_script:
    - apk add --no-cache curl jq python3 py-pip
    - pip install awscli
    - eval $(aws ecr get-login --no-include-email --region $AWS_REGION | sed 's|https://||')
  script:
    - aws s3 cp public/ s3://$S3_BUCKET_NAME/ --recursive --include "*"
  only:
    - master